owner: theswissbay
repo: status

user-agent: theswissbay

sites:
  - name: Website
    url: https://theswissbay.ch/
    icon: https://theswissbay.ch/favicon.ico
  - name: PDF archive
    url: https://theswissbay.ch/pdf/changelog.html
    icon: https://theswissbay.ch/favicon.ico
  - name: 4id
    url: https://fourid.theswissbay.ch/
    icon: https://fourid.theswissbay.ch/static/img/ico.webp
  - name: GitLab
    url: https://gitlab.theswissbay.ch/users/sign_in
    icon: https://gitlab.theswissbay.ch/assets/favicon-72a2cad5025aa931d6ea56c3201d1f18e68a8cd39788c7c80d5b2b82aa5143ef.png
  - name: GitLab SSH
    check: "tcp-ping"
    url: 81.6.2.165
    port: 10090
    icon: https://gitlab.theswissbay.ch/assets/favicon-72a2cad5025aa931d6ea56c3201d1f18e68a8cd39788c7c80d5b2b82aa5143ef.png

status-website:
  # cname: demo.upptime.js.org
  logoUrl: https://theswissbay.ch/favicon.ico
  baseUrl: /status
  name: The Swiss Bay
  theme: night
  introTitle: "Status monitor"
  introMessage: "This service is hosted on GitHub to monitor our services as they are seen from the Internet."
  navbar:
    - title: The Swiss Bay
      href: https://theswissbay.ch/
    - title: PDF archive
      href: https://theswissbay.ch/pdf
    - title: 4id
      href: https://fourid.theswissbay.ch/
    - title: GitLab
      href: https://gitlab.theswissbay.ch/
    - title: Incident history
      href: https://github.com/$OWNER/$REPO/issues

assignees:
  - tsb-theswissguy
