owner: theswissbay
repo: status

user-agent: theswissbay

sites:
  - name: Website
    url: https://theswissbay.ch/
    icon: https://theswissbay.ch/favicon.ico
  - name: PDF archive
    url: https://theswissbay.ch/pdf/changelog.html
    icon: https://theswissbay.ch/favicon.ico
  - name: Arch Linux mirror
    url: https://theswissbay.ch/archlinux/lastupdate
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Archlinux-icon-crystal-64.svg/65px-Archlinux-icon-crystal-64.svg.png
  - name: 4id
    url: https://fourid.theswissbay.ch/
    icon: https://fourid.theswissbay.ch/static/img/ico.webp
  - name: GitLab
    url: https://gitlab.theswissbay.ch/users/sign_in
    icon: https://gitlab.theswissbay.ch/assets/favicon-72a2cad5025aa931d6ea56c3201d1f18e68a8cd39788c7c80d5b2b82aa5143ef.png
  - name: GitLab SSH
    check: "tcp-ping"
    url: 85.195.200.187
    port: 10090
    icon: https://gitlab.theswissbay.ch/assets/favicon-72a2cad5025aa931d6ea56c3201d1f18e68a8cd39788c7c80d5b2b82aa5143ef.png

status-website:
  # cname: demo.upptime.js.org
  logoUrl: https://theswissbay.ch/favicon.ico
  baseUrl: /status
  name: The Swiss Bay
  theme: night
  introTitle: "Status monitor"
  introMessage: "This service is hosted on GitHub to monitor our endpoints as they are seen from the Internet."
  navbar:
    - title: Website
      href: https://theswissbay.ch/
      target: _blank
    - title: PDF archive
      href: https://theswissbay.ch/pdf/
      target: _blank
    - title: Arch Linux mirror
      href: https://theswissbay.ch/archlinux/
      target: _blank
    - title: 4id
      href: https://fourid.theswissbay.ch/
      target: _blank
    - title: GitLab
      href: https://gitlab.theswissbay.ch/
      target: _blank
    - title: Incident history
      href: https://github.com/$OWNER/$REPO/issues
      target: _blank

workflowSchedule:
  uptime: "0 0 29 2 1"

assignees:
  - tsb-theswissguy
